version: "2"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_HOST: ${VIRTUAL_HOST}
      HTTPS_METHOD: noredirect
    restart: always

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs:rw
    environment:
      - DEFAULT_EMAIL=${EMAIL}
      - NGINX_PROXY_CONTAINER=nginx-proxy
    depends_on:
      - nginx-proxy
    restart: always

  app:
    image: slack_doorman:latest
    build:
      context: .
      network: host
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=4000
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${EMAIL}
    ports:
      - 4000:4000
    depends_on:
      - nginx-proxy-acme
    network_mode: "host"

volumes:
  conf:
  certs:
  vhost:
  html:
  acme: