version: '3'

services:
  app:
    image: slack_doorman:latest
    build:
      context: .
      network: host
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=4000
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${EMAIL}
    ports:
      - 4000:4000
    dns: 8.8.8.8
    network_mode: "host"

networks:
  default:
    external:
      name: nginx-proxy
